### ISSUE TITLE
[Egg Request]: DayZ Stable

### ISSUE THREAD

**Issue by Brophy** [pelican-eggs/games-steamcmd#20]
### Does this expand an already existing service

Yes

### Link to a game or software

https://dayz.com/

### Links for the download

https://steamdb.info/app/223350/info/

### Links for the install docs

https://community.bistudio.com/wiki/DayZ:Hosting_a_Linux_Server

As per the now archived repo: https://github.com/pelican-eggs/eggs/issues/2749

**Comment by Brophy** [comment]
I have modified the experimental egg to use the stable ID, I've added a variable for you to add your query port (to make it discoverable, just make sure you also assign the additional port during setup) and I've adjusted the installer script to add the `steamQueryPort` variable to the serverDZ.cfg after it's creation, as its not there by default.

I've not had time to experiment with mods, but I thought I would put here what I've played around with so far, so people can expand upon it.

It seems to work ok:
![image](https://github.com/pelican-eggs/games-steamcmd/assets/123881/d184c41d-870c-4bf6-8e7b-176843af57c1)

Egg:
[egg-dayz-stable.json](https://github.com/pelican-eggs/games-steamcmd/files/15349718/egg-dayz-stable.json)

**Comment by lilkingjr1** [comment]
Now that I'm done with my college semester, I'll hopefully have time to work officially on this soon™.

**Comment by killerwerdna** [comment]
im currently building a server on linux pterodactyl but keep getting stuck 
![image](https://github.com/pelican-eggs/games-steamcmd/assets/170500947/26cf94f7-ed5f-4134-ae44-2a3030c98010)
at this

**Comment by Brophy** [comment]
@killerwerdna are you using an account that requires 2FA? That's normally why it gets stuck there.

**Comment by killerwerdna** [comment]
@Brophy its a brand new account with no 2FA

**Comment by killerwerdna** [comment]
![image](https://github.com/pelican-eggs/games-steamcmd/assets/170500947/c640edd7-b967-4d45-b940-42508b181067)
im getting this but the username and pass is definitely not wrong

**Comment by killerwerdna** [comment]
![image](https://github.com/pelican-eggs/games-steamcmd/assets/170500947/5f9d0028-54df-449a-a2e3-3316239cf107)
ye getting this now password is 100% correct

**Comment by Brophy** [comment]
@killerwerdna are you using my egg? It looks like you've modified the `[Advanced] DayZ SA Dedicated Server App ID` to `221100` when you require `223350` (default value) for the stable server files.

**Comment by killerwerdna** [comment]
this has changed on its own somehow we have had this issue a fair bit

**Comment by IndaQLV** [comment]
> ![image](https://private-user-images.githubusercontent.com/170500947/332715114-5f9d0028-54df-449a-a2e3-3316239cf107.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjcyNTksIm5iZiI6MTcxNjM2Njk1OSwicGF0aCI6Ii8xNzA1MDA5NDcvMzMyNzE1MTE0LTVmOWQwMDI4LTU0ZGYtNDQ5YS1hMmUzLTMzMTYyMzljZjEwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwODM1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTg2MjIwNTQ2NDg1YjUxMTc4ZDIzYjQ3M2I5NmM2M2E2MzEwNzM2NjBmNTkxZTVhN2IxOTYxOTRhNTVhOGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qqc9u-a7T8QRpUFw8Xol_qAMz-eYvsWwnh9PVf_5qPE) ye getting this now password is 100% correct

That account needs to own dayz in order to download the server.

**Comment by killerwerdna** [comment]
![image](https://github.com/pelican-eggs/games-steamcmd/assets/170500947/a6bec59b-1b93-4327-bab9-6333b8dab023)
well i fixed the app id and got this far

**Comment by killerwerdna** [comment]
![image](https://github.com/pelican-eggs/games-steamcmd/assets/170500947/4ac265a3-e0b4-4856-8814-53285f8dda5d)
nvm made it this far so far

**Comment by CrnaStrela94** [comment]
@killerwerdna  i don't think so tho mods goes under update every time server starts and it will check true workshop and for that u need account that have the game

**Comment by DemOnJR** [comment]
Someone managed to create an DayZ Stable Build egg?

**Comment by Z3r0s** [comment]
> Someone managed to create an DayZ Stable Build egg?

We made a semi-stable one but mods are botched rn.

**Comment by lilkingjr1** [comment]
Just an update, I’ve finally gotten around to working on this. Just slowed down a bit trying to verify mods are working (stupid Steam Guard), but it’s mostly going well. Sorry for the wait.

**Comment by DemOnJR** [comment]
> Just an update, I’ve finally gotten around to working on this. Just slowed down a bit trying to verify mods are working (stupid Steam Guard), but it’s mostly going well. Sorry for the wait.

I saw that also the Steam Guard is blocking the console and the installation of the server of the updating the mods

**Comment by HOZAMA** [comment]
@lilkingjr1 Good afternoon! Are there any approximate release dates for the egg for the stable version of DayZ?

I'm looking forward to the release of this.

And thank you in advance for your work!

**Comment by DemOnJR** [comment]
Nothing new? i can also help with tests and maybe solving some bugs...

**Comment by lilkingjr1** [comment]
Thank you everyone for your patience! As you can see above, I have finally submitted a PR to update the Egg to support the native Linux dedicated server on the Stable branch. Please check it out, test it, and leave any remarks on the PR (not here).

Looking at the changes in the PR, I know it seems like not much was changed, especially given the time it took me to complete it. Please understand many rabbit holes were chased during development (especially with the Egg's accompanying Docker image), which took up a lot of my time. These include:
- Checking if SteamCMD fixed its crashing bug when logging in with real Steam accounts, and removing the `numactl` workaround for this.
- Attempting to completely rewrite the image entrypoint to dynamically compile and use a SteamCMD script to update the server and mods in one run instead of multiple SteamCMD calls. This was done in effort to possibly make updating with Steam Guard on possible/easier. However, this was taking too much time to perfect and would require me to completely rewrite or throw out my SteamCMD error handling system, which I find more valuable keeping at the moment.
- Attempting to symlink mod folders instead of moving them from `./Steam/steamapps/workshop`. This also would have caused a lot of the code to be rewritten to fix something small that isn't really an issue, so I ultimately decided to shelve that for now. The panel's file viewer also doesn't follow symlinks unfortunately, potentially causing confusion.
- Battling with the accuracy of the BIKI (yet again...) regarding launch parameters. It states quotations should be used around certain flags (which makes sense given that mod lists are `;` separated), but this is not true in practice (even though it *is* true with Arma 3, making things more confusing for me).

**Comment by penalte** [comment]
there is a bug in "[Advanced] Server-Side Only Mods" only read the first mod, also in DayZ linux wiki they say to not use "@" and to put the launch parameter mod and servermod in quotes "" here it is https://community.bistudio.com/wiki/DayZ:Hosting_a_Linux_Server.
About the bug is something to do with 
"# Replace Startup Variables
modifiedStartup=`eval echo $(echo ${STARTUP} | sed -e 's/{{/${/g' -e 's/}}/}/g')`"

LOGS:
[UPDATE]: Steam Workshop mod update check complete!
/entrypoint.sh: line 283: @3098001210: command not found
/entrypoint.sh: line 283: @2464526692: command not found
/entrypoint.sh: line 283: -dologs: command not found
[STARTUP]: Starting server with the following startup command:
./DayZServer -port=2302 -profiles=profiles -bepath=./ -config=serverDZ.cfg -mod= -serverMod=@2960586913
