### ISSUE TITLE
[Bug]: egg-pterodactyl-arma3 - Headless Clients and localClient is getting overwrited

### ISSUE THREAD

**Issue by BlockyBlockling** [pelican-eggs/games-steamcmd#91]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

arma3

### Modified

No, I did not modify the egg

### Expected Behavior

Have an Variable for headlessClients config Entry and for localClient Config Entry.

### Actual Behavior

Both are always getting overwritten with `{ "127.0.0.1" }`

### Steps To Reproduce

Download the Egg
Change the Values in the server.cfg
Start the Server
Check server.cfg

### Install logs

https://ptero.co/savarikemo

**Comment by lilkingjr1** [comment]
This is expected behavior of the Egg and it will not be adjusted. The Egg supports a feature where you can run Headless Clients in parallel with the server within the same container. Therefore, the server must be configured to look for them locally using the loopback address. Hosting Headless Clients externally (ie. at a different address) can introduce latency and diminishing returns, so it is not generally recommended. However, if you still wish to do this, you can simply edit the Egg by removing the following two lines from the "Configuration Files" section:
```diff
+ "maxPlayers": "maxPlayers = {{env.MAX_PLAYERS}};"  <- Remove trailing comma
- "headlessClients": "headlessClients[] = { \"127.0.0.1\" };",
- "localClient": "localClient[] = { \"127.0.0.1\" };"
```
